deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Update to the latest version, which uses Node.js 20
      with:
        repository: https://github.com/jaykumsi/tinitiate-aws-glue.git
        ref: main
        
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2  # Update to the latest version
      with:
        name: unzip_glue_job.py
        
    - name: Set up AWS credentials
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        mkdir -p ~/.aws
        touch ~/.aws/credentials
        echo "[default]
        aws_access_key_id = $AWS_ACCESS_KEY_ID
        aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" > ~/.aws/credentials
    - name: Upload to S3
      run: aws s3 cp unzip_glue_job.py s3://tini-d-gluebucket-001/py_scripts/unzip_glue_job.py --region us-east-1
    - name: Update Glue job
      run: |
        aws glue update-job --job-name "UNZIP_INVOICE_Jan_31" --job-update \
"Role=AWSGlueServiceRole,Command={Name=glueetl,ScriptLocation=s3://tini-d-gluebucket-001/py_scripts/unzip_glue_job.py}" \
--region us-east-1
    - name: Cleanup
      run: rm -rf ~/.aws  
      
    