name: AWS Glue Job

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  run-glue-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Adjust the region as needed

    - name: Run AWS Glue Job
      run: |
        aws glue start-job-run --job-name unzip_glue_job.py
